name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version:
            - 16.x
            - 18.x
            - 20.x
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 18.x
          - 16.x
          - 14.x
        include:
          - os: windows-latest
            node: 18.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version:
            - 16.x
            - 18.x
            - 20.x
      - name: Install latest NPM
        run: bun i -g npm@latest --no-save
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
